---
- name: Restart nats-server
  ansible.builtin.service:
    name: nats-server
    state: restarted

- name: Reload nats-server
  ansible.builtin.service:
    name: nats-server
    state: reloaded

- name: Reload daemon nats-server
  ansible.builtin.systemd:
    state: stopped
    daemon_reload: true
    name: nats-server

- name: Reload daemon nats-exporter
  ansible.builtin.systemd:
    state: stopped
    daemon_reload: true
    name: nats-exporter
